export const API_BASE_CANDIDATES = [
  import.meta.env.VITE_API_BASE_URL,
  "https://iith-one.vercel.app",
  "https://iith-diwme0371-udayprakashchamakuri-5279s-projects.vercel.app",
  "https://skill-deploy-0ppx8gx7h4-n1pkbd8p3.vercel.app",
  "https://skill-deploy-0ppx8gx7h4.vercel.app",
  "https://skill-deploy-0pp-git-1c911a-udayprakashchamakuri-5279s-projects.vercel.app",
].filter(Boolean);

export const API_BASE = API_BASE_CANDIDATES[0];

export const NAV_ITEMS = [
  { id: "simulation", label: "Discussion", icon: "hub" },
  { id: "intelligence", label: "Overview", icon: "psychology" },
  { id: "agents", label: "Team", icon: "groups" },
  { id: "risk", label: "Risks", icon: "shield" },
];

export const AGENT_META = {
  "CEO Agent": {
    initials: "EX1",
    accent: "#ffe16d",
    symbol: "crown",
    label: "CEO",
    title: "Final decision maker",
    boardRole: "Chief Executive Officer",
  },
  "Startup Builder Agent": {
    initials: "BLD",
    accent: "#ff9f59",
    symbol: "rocket_launch",
    label: "Startup Builder",
    title: "Fast execution",
    boardRole: "Startup Builder",
  },
  "Market Research Agent": {
    initials: "RSH",
    accent: "#9ac9ff",
    symbol: "travel_explore",
    label: "Market Research",
    title: "Customer demand research",
    boardRole: "Market Research",
  },
  "Finance Agent": {
    initials: "FIN",
    accent: "#00ff94",
    symbol: "leaderboard",
    label: "Finance",
    title: "Money and budget",
    boardRole: "Finance",
  },
  "Marketing Agent": {
    initials: "MKT",
    accent: "#ddb7ff",
    symbol: "campaign",
    label: "Marketing",
    title: "Messaging and demand",
    boardRole: "Marketing",
  },
  "Pricing Agent": {
    initials: "PRC",
    accent: "#ffdb3c",
    symbol: "sell",
    label: "Pricing",
    title: "Price planning",
    boardRole: "Pricing",
  },
  "Supply Chain Agent": {
    initials: "OPS",
    accent: "#7be7d4",
    symbol: "local_shipping",
    label: "Operations",
    title: "Delivery and operations",
    boardRole: "Supply Chain",
  },
  "Hiring Agent": {
    initials: "HIR",
    accent: "#f7a6c6",
    symbol: "groups",
    label: "Hiring",
    title: "Team planning",
    boardRole: "Hiring",
  },
  "Risk Agent": {
    initials: "RSK",
    accent: "#ff8f8f",
    symbol: "security",
    label: "Risk",
    title: "What could go wrong",
    boardRole: "Risk",
  },
  "Sales Strategy Agent": {
    initials: "SLS",
    accent: "#ffb870",
    symbol: "handshake",
    label: "Sales",
    title: "Sales plan",
    boardRole: "Sales Strategy",
  },
};

export const DEMO_CASES = [
  {
    id: "healthcare-saas",
    label: "AI software for hospitals",
    summary: "A startup deciding whether to expand into healthcare with limited cash and heavier compliance needs.",
    form: {
      company_name: "HelixOps AI",
      industry: "Business software",
      region: "North America",
      company_stage: "Seed",
      business_problem:
        "We are a young software company thinking about selling our AI product to mid-sized hospitals. Our product helps hospitals handle insurance approval work faster, but this new market would require more integrations, a longer sales process, stronger compliance controls, and better customer support. We have about 11 months of cash left, our profit margin is around 68%, we expect it will take 15 months to earn back sales and marketing costs, and we are considering charging about $28,000 per customer each year. The team needs to decide whether to launch now, move forward with changes, or wait.",
      objectives:
        "Grow revenue, enter a new market carefully, protect cash, avoid compliance mistakes",
      current_constraints:
        "Small team, limited runway, long sales cycle, more customer support required",
      extra_context: "",
      runway_months: "11",
      gross_margin: "68",
      cac_payback_months: "15",
      price_point: "28000",
      variation_name: "Healthcare downside case",
      variation_budget_change_pct: "-20",
      variation_market_condition: "bearish",
      variation_competition_level: "high",
      variation_pricing_change_pct: "-10",
      variation_notes: "Assume buyers slow down and compliance work takes longer than expected.",
    },
  },
  {
    id: "college-game-center",
    label: "Game center near a college",
    summary: "A local entertainment business deciding whether to open near a campus and how to price memberships.",
    form: {
      company_name: "Campus Arena",
      industry: "Entertainment",
      region: "India",
      company_stage: "Idea",
      business_problem:
        "I want to start a game center near a college. The plan is to offer PC gaming, console gaming, small tournaments, and snacks. The area has strong student traffic, but students are price-sensitive and the business would need a decent upfront fit-out, gaming equipment, rent, and staff. I need to know whether this can work, how risky it is, and what kind of pricing and launch plan would make sense.",
      objectives: "Reach break-even fast, attract repeat visits, build a student community",
      current_constraints: "Limited startup capital, uncertain weekday demand, high upfront equipment cost",
      extra_context:
        "The location is close to hostels and coaching centers, and I may also host weekend esports events.",
      runway_months: "10",
      gross_margin: "55",
      cac_payback_months: "6",
      price_point: "299",
      variation_name: "Low-demand semester break case",
      variation_budget_change_pct: "-15",
      variation_market_condition: "bearish",
      variation_competition_level: "medium",
      variation_pricing_change_pct: "-5",
      variation_notes: "Assume foot traffic drops during exam season and semester breaks.",
    },
  },
  {
    id: "d2c-skincare",
    label: "Online skincare brand",
    summary: "A direct-to-consumer brand testing whether it should scale ads and add new products.",
    form: {
      company_name: "PureGlow Labs",
      industry: "Consumer goods",
      region: "Asia-Pacific",
      company_stage: "Pre-seed",
      business_problem:
        "We sell a small set of skincare products online and are considering whether to increase ad spend and launch two new products before the festive season. Sales have been growing, but return rates, ad costs, and repeat purchase rates are still uneven. We need to decide whether to scale now or tighten the business first.",
      objectives: "Grow monthly sales, improve repeat purchases, launch before the festive season",
      current_constraints: "Rising ad costs, limited inventory budget, uncertain repeat rate",
      extra_context: "Most sales come from Instagram and our own website, and our best-selling product is a vitamin C serum.",
      runway_months: "9",
      gross_margin: "62",
      cac_payback_months: "8",
      price_point: "1499",
      variation_name: "Ad costs spike case",
      variation_budget_change_pct: "-10",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "0",
      variation_notes: "Assume paid social costs rise sharply for the next 90 days.",
    },
  },
  {
    id: "ev-charging-app",
    label: "EV charging app partnership",
    summary: "A mobility startup considering a city expansion through charger-network partnerships.",
    form: {
      company_name: "VoltPath",
      industry: "Mobility technology",
      region: "Europe",
      company_stage: "Series A",
      business_problem:
        "We have an app that helps electric vehicle drivers find and book charging slots. We are considering entering two more cities through partnerships with charging-station operators. The upside is faster growth, but integration work, partner dependence, and customer support complexity could all increase. We need a decision on whether to expand now.",
      objectives: "Expand city coverage, grow active users, build strong partner relationships",
      current_constraints: "Integration complexity, partner dependency, limited operations bandwidth",
      extra_context: "Our current cities perform well on weekends but weekday bookings are still inconsistent.",
      runway_months: "14",
      gross_margin: "58",
      cac_payback_months: "11",
      price_point: "120",
      variation_name: "Partner delay case",
      variation_budget_change_pct: "-5",
      variation_market_condition: "base",
      variation_competition_level: "medium",
      variation_pricing_change_pct: "3",
      variation_notes: "Assume one large charging partner delays integration by two months.",
    },
  },
  {
    id: "test-prep-center",
    label: "Test prep and tutoring center",
    summary: "An education business deciding whether to open a physical center and offer hybrid classes.",
    form: {
      company_name: "ScoreBridge",
      industry: "Education",
      region: "India",
      company_stage: "Established business",
      business_problem:
        "We run a small online test-prep business and are thinking about opening a physical tutoring center near a dense student neighborhood. The center could improve trust and retention, but rent, faculty hiring, and operations would become much heavier. We need to decide whether a physical center makes sense now and what a safe first step would look like.",
      objectives: "Increase enrollment, improve retention, build local brand trust",
      current_constraints: "Faculty hiring risk, rent commitments, uneven enrollment by month",
      extra_context: "Students mainly come for engineering and government exam preparation, and parents care a lot about reputation and results.",
      runway_months: "13",
      gross_margin: "48",
      cac_payback_months: "5",
      price_point: "18000",
      variation_name: "Slow enrollment case",
      variation_budget_change_pct: "-20",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "-8",
      variation_notes: "Assume enrollment fills slower than expected in the first two months.",
    },
  },
  {
    id: "cloud-kitchen",
    label: "Cloud kitchen expansion",
    summary: "A food business deciding whether to open a second kitchen and add aggregator-heavy growth.",
    form: {
      company_name: "Urban Tiffin Co.",
      industry: "Food service",
      region: "Middle East & Africa",
      company_stage: "Established business",
      business_problem:
        "Our cloud kitchen has built a loyal local customer base, and we are considering opening a second kitchen to cover another delivery zone. The new kitchen could increase revenue, but food-delivery commissions, staffing, and quality control are already under pressure. We need to decide whether expansion now is smart or too risky.",
      objectives: "Grow order volume, keep food quality high, maintain profit",
      current_constraints: "Delivery app commissions, staffing gaps, quality consistency across locations",
      extra_context: "Dinner orders are strong, but lunch demand is still inconsistent and customer ratings drop when delivery times slip.",
      runway_months: "8",
      gross_margin: "44",
      cac_payback_months: "4",
      price_point: "12",
      variation_name: "Commission pressure case",
      variation_budget_change_pct: "-12",
      variation_market_condition: "base",
      variation_competition_level: "high",
      variation_pricing_change_pct: "5",
      variation_notes: "Assume delivery platforms raise commission and customer discounts become harder to sustain.",
    },
  },
];

export const sampleProblem = DEMO_CASES[0].form.business_problem;

export const defaultTimeline = [
  { round: 1, synopsis: "Round 1 - each advisor shares an opening view." },
  { round: 2, synopsis: "Round 2 - the team challenges weak assumptions." },
  { round: 3, synopsis: "Round 3 - the team agrees on next steps." },
];
